import type { Axis, Pole, CardInfo as ScoringCardInfo } from "../valueAxisScoring";

export type CardInfo = ScoringCardInfo;

export function getCardImageUrl(cardId: number): string {
  return `/cards/card_${cardId.toString().padStart(2, "0")}.png`;
}

export const cardDict: { [id: number]: CardInfo } = {
  0: { japanese: '海外就職', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "AS", pole: "C", score: 5 }, { axis: "UN", pole: "U", score: 2 }, { axis: "IT", pole: "I", score: 2 }] },
  1: { japanese: '将来の夢への直結度', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "AS", pole: "C", score: 2 }] },
  2: { japanese: '世界ランキング', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "AS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 3 }] },
  3: { japanese: '大学の知名度', axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  4: { japanese: '学問の専門性', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "AS", pole: "C", score: 1 }, { axis: "IT", pole: "I", score: 3 }] },
  5: { japanese: '批判的思考力', axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "AS", pole: "C", score: 2 }, { axis: "IT", pole: "I", score: 3 }] },
  6: { japanese: '成績', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "C", score: 2 }] },
  7: { japanese: '実践型', axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "AS", pole: "C", score: 3 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 2 }] },
  8: { japanese: '評価方法', axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "IT", pole: "I", score: 1 }] },
  9: { japanese: '準備・計画努力型', axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "AS", pole: "S", score: 1 }, { axis: "IT", pole: "I", score: 4 }] },
  10: { japanese: '大学院進学率', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 1 }] },
  11: { japanese: '挫折経験', axisScores: [{ axis: "AS", pole: "C", score: 5 }, { axis: "IT", pole: "I", score: 3 }] },
  12: { japanese: '留学スタイル（正規・交換）', axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "AS", pole: "C", score: 1 }] },
  13: { japanese: '留学期間', axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "AS", pole: "C", score: 2 }] },
  14: { japanese: '就職率', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "AS", pole: "S", score: 4 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 1 }] },
  15: { japanese: 'キャリアの汎用性の高さ', axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "AS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 1 }] },
  16: { japanese: '資格', axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "AS", pole: "S", score: 4 }, { axis: "IT", pole: "I", score: 3 }] },
  17: { japanese: '前例の多さ', axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "AS", pole: "S", score: 5 }, { axis: "IT", pole: "T", score: 2 }] },
  18: { japanese: 'コスパ・タイパ', axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "AS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 2 }] },
  19: { japanese: '英語力', axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "AS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 1 }] },
  20: { japanese: '言語の学びやすさ', axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "AS", pole: "S", score: 4 }, { axis: "IT", pole: "T", score: 1 }] },
  21: { japanese: '学費', axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "AS", pole: "S", score: 4 }, { axis: "IT", pole: "I", score: 1 }] },
  22: { japanese: '物価', axisScores: [{ axis: "AS", pole: "S", score: 3 }, { axis: "UN", pole: "N", score: 1 }] },
  23: { japanese: '現地での収入源', axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "AS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 2 }] },
  24: { japanese: '奨学金', axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "AS", pole: "S", score: 3 }, { axis: "IT", pole: "I", score: 2 }] },
  25: { japanese: '学校のサポート', axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "AS", pole: "S", score: 5 }, { axis: "IT", pole: "T", score: 3 }] },
  26: { japanese: 'ガクチカ', axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "AS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 1 }] },
  27: { japanese: '地方', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "AS", pole: "C", score: 3 }, { axis: "UN", pole: "N", score: 5 }, { axis: "IT", pole: "I", score: 1 }] },
  28: { japanese: '街の雰囲気（歴史的・モダン）', axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "AS", pole: "S", score: 1 }, { axis: "UN", pole: "N", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  29: { japanese: '自然の近さ', axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "UN", pole: "N", score: 5 }] },
  30: { japanese: '国際性', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "C", score: 2 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "T", score: 3 }] },
  31: { japanese: '多様性', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "AS", pole: "C", score: 3 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "T", score: 3 }] },
  32: { japanese: '留学先の国民性', axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "IT", pole: "T", score: 2 }] },
  33: { japanese: '英語のアクセント', axisScores: [{ axis: "AS", pole: "C", score: 2 }] },
  34: { japanese: 'アルバイト', axisScores: [{ axis: "AS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  35: { japanese: '課外活動', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 4 }] },
  36: { japanese: 'スポーツ', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "IT", pole: "T", score: 4 }] },
  37: { japanese: '現地の友人関係', axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "AS", pole: "C", score: 1 }, { axis: "IT", pole: "T", score: 5 }] },
  38: { japanese: '精神的成長', axisScores: [{ axis: "AS", pole: "C", score: 4 }, { axis: "IT", pole: "I", score: 3 }] },
  39: { japanese: 'キャラ変（から破り）', axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "AS", pole: "C", score: 4 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 2 }] },
  40: { japanese: '芸術', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "AS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "I", score: 1 }] },
  41: { japanese: '都市', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "UN", pole: "U", score: 5 }, { axis: "IT", pole: "T", score: 1 }] },
  42: { japanese: '部活', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "IT", pole: "T", score: 5 }] },
  43: { japanese: '日本人の少なさ', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "C", score: 5 }, { axis: "UN", pole: "N", score: 1 }, { axis: "IT", pole: "I", score: 4 }] },
  44: { japanese: '治安の良さ', axisScores: [{ axis: "AS", pole: "S", score: 5 }] },
  45: { japanese: '衛生面・綺麗さ', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "S", score: 4 }, { axis: "UN", pole: "U", score: 1 }] },
  46: { japanese: '医療技術', axisScores: [{ axis: "AS", pole: "S", score: 5 }, { axis: "UN", pole: "U", score: 1 }] },
  47: { japanese: '気候の快適さ', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "AS", pole: "S", score: 3 }] },
  48: { japanese: '住居（寮・シェアハウス・ホームステイ）', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 3 }] },
  49: { japanese: '施設の充実度', axisScores: [{ axis: "AS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 2 }] },
  50: { japanese: '日本からの距離', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  51: { japanese: '日本との時差', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  52: { japanese: '家族や恋人との連絡頻度', axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "AS", pole: "S", score: 4 }, { axis: "IT", pole: "T", score: 3 }] },
  53: { japanese: '親日性', axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "AS", pole: "S", score: 4 }, { axis: "IT", pole: "T", score: 2 }] },
  54: { japanese: '日本との政治的関係', axisScores: [{ axis: "AS", pole: "S", score: 3 }] },
  55: { japanese: '食の豊かさ', axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "AS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  56: { japanese: '娯楽', axisScores: [{ axis: "CL", pole: "L", score: 5 }, { axis: "AS", pole: "S", score: 1 }, { axis: "UN", pole: "U", score: 4 }, { axis: "IT", pole: "T", score: 3 }] },
  57: { japanese: 'ナイトライフ', axisScores: [{ axis: "CL", pole: "L", score: 5 }, { axis: "AS", pole: "C", score: 2 }, { axis: "UN", pole: "U", score: 5 }, { axis: "IT", pole: "T", score: 4 }] },
  58: { japanese: '私生活と勉強のバランス', axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "AS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  59: { japanese: 'クラス規模', axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "AS", pole: "S", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  60: { japanese: '教授との距離', axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "AS", pole: "S", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  61: { japanese: '移動手段', axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "AS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 3 }] },
};
