import type { Axis, Pole, CardInfo as ScoringCardInfo } from "../valueAxisScoring";

export type CardInfo = ScoringCardInfo;

export function getCardImageUrl(cardId: number): string {
  return `/cards/card_${cardId.toString().padStart(2, "0")}.png`;
}

export const cardDict: { [id: number]: CardInfo } = {
  0:  { japanese: "時間を大切に", english: "Time Conscious", axisScores: [{ axis: "LI", pole: "L", score: 8 }, { axis: "ES", pole: "S", score: 6 }] },
  1:  { japanese: "承認", english: "Acknowledgement", axisScores: [{ axis: "AC", pole: "C", score: 7 }, { axis: "DW", pole: "D", score: 6 }] },
  2:  { japanese: "行動", english: "Action", axisScores: [{ axis: "DW", pole: "D", score: 9 }] },
  3:  { japanese: "冒険", english: "Adventure", axisScores: [{ axis: "ES", pole: "E", score: 10 }] },
  4:  { japanese: "利他的", english: "Altruistic", axisScores: [{ axis: "AC", pole: "C", score: 9 }] },
  5:  { japanese: "志・野心", english: "Ambition", axisScores: [{ axis: "DW", pole: "D", score: 10 }] },
  6:  { japanese: "向上心", english: "Aspiration", axisScores: [{ axis: "DW", pole: "D", score: 9 }] },
  7:  { japanese: "自律", english: "Autonomy", axisScores: [{ axis: "AC", pole: "A", score: 10 }] },
  8:  { japanese: "挑戦", english: "Challenge", axisScores: [{ axis: "ES", pole: "E", score: 8 }, { axis: "DW", pole: "D", score: 8 }] },
  9:  { japanese: "変化", english: "Change", axisScores: [{ axis: "ES", pole: "E", score: 9 }] },
  10: { japanese: "心地よさ", english: "Comfortableness", axisScores: [{ axis: "ES", pole: "S", score: 9 }, { axis: "DW", pole: "W", score: 7 }] },
  11: { japanese: "コミットメント", english: "Commitment", axisScores: [{ axis: "AC", pole: "C", score: 8 }, { axis: "ES", pole: "S", score: 6 }] },
  12: { japanese: "コミュニケーション", english: "Communication", axisScores: [{ axis: "AC", pole: "C", score: 9 }] },
  13: { japanese: "冷静", english: "Composure", axisScores: [{ axis: "DW", pole: "W", score: 8 }, { axis: "ES", pole: "S", score: 6 }] },
  14: { japanese: "一貫性", english: "Consistency", axisScores: [{ axis: "ES", pole: "S", score: 9 }, { axis: "LI", pole: "L", score: 6 }] },
  15: { japanese: "貢献", english: "Contribution", axisScores: [{ axis: "AC", pole: "C", score: 8 }, { axis: "DW", pole: "W", score: 5 }] },
  16: { japanese: "協力", english: "Cooperation", axisScores: [{ axis: "AC", pole: "C", score: 10 }] },
  17: { japanese: "礼儀・礼節", english: "Courtesy", axisScores: [{ axis: "AC", pole: "C", score: 8 }, { axis: "ES", pole: "S", score: 5 }] },
  18: { japanese: "創造性", english: "Creativity", axisScores: [{ axis: "LI", pole: "I", score: 10 }] },
  19: { japanese: "好奇心", english: "Curiousity", axisScores: [{ axis: "ES", pole: "E", score: 8 }, { axis: "LI", pole: "I", score: 7 }] },
  20: { japanese: "規律", english: "Discipline", axisScores: [{ axis: "LI", pole: "L", score: 10 }, { axis: "ES", pole: "S", score: 7 }] },
  21: { japanese: "多様性", english: "Diversity", axisScores: [{ axis: "ES", pole: "E", score: 7 }, { axis: "AC", pole: "C", score: 6 }] },
  22: { japanese: "義理人情", english: "Duty and Humanity", axisScores: [{ axis: "AC", pole: "C", score: 7 }, { axis: "ES", pole: "S", score: 7 }] },
  23: { japanese: "有効性・効率", english: "Effectiveness", axisScores: [{ axis: "LI", pole: "L", score: 9 }, { axis: "DW", pole: "D", score: 7 }] },
  24: { japanese: "努力", english: "Effort", axisScores: [{ axis: "DW", pole: "D", score: 8 }] },
  25: { japanese: "共感", english: "Empathy", axisScores: [{ axis: "AC", pole: "C", score: 9 }, { axis: "DW", pole: "W", score: 6 }] },
  26: { japanese: "エンパワーメント", english: "Empowerment", axisScores: [{ axis: "AC", pole: "C", score: 7 }, { axis: "DW", pole: "D", score: 6 }] },
  27: { japanese: "励まし", english: "Encouregement", axisScores: [{ axis: "AC", pole: "C", score: 8 }] },
  28: { japanese: "平等・公平性", english: "Equality", axisScores: [{ axis: "AC", pole: "C", score: 7 }] },
  29: { japanese: "躍動的な人生", english: "Exciting Life", axisScores: [{ axis: "ES", pole: "E", score: 9 }] },
  30: { japanese: "経験", english: "Experience", axisScores: [{ axis: "ES", pole: "E", score: 8 }] },
  31: { japanese: "公正性・公平性", english: "Fairness", axisScores: [{ axis: "AC", pole: "C", score: 6 }] },
  32: { japanese: "家族", english: "Family", axisScores: [{ axis: "AC", pole: "C", score: 10 }] },
  33: { japanese: "フォロワーシップ", english: "Followership", axisScores: [{ axis: "AC", pole: "C", score: 8 }] },
  34: { japanese: "率直さ", english: "Frankness", axisScores: [{ axis: "AC", pole: "A", score: 7 }] },
  35: { japanese: "自由", english: "Freedom", axisScores: [{ axis: "AC", pole: "A", score: 10 }] },
  36: { japanese: "友情・仲間", english: "Friendship", axisScores: [{ axis: "AC", pole: "C", score: 9 }] },
  37: { japanese: "全力", english: "Full Strength", axisScores: [{ axis: "DW", pole: "D", score: 8 }] },
  38: { japanese: "優しさ", english: "Gentleness", axisScores: [{ axis: "AC", pole: "C", score: 8 }, { axis: "DW", pole: "W", score: 6 }] },
  39: { japanese: "グローバル", english: "Global", axisScores: [{ axis: "ES", pole: "E", score: 8 }] },
  40: { japanese: "感謝", english: "Gratitude", axisScores: [{ axis: "DW", pole: "W", score: 9 }] },
  41: { japanese: "成長", english: "Growth", axisScores: [{ axis: "DW", pole: "D", score: 9 }] },
  42: { japanese: "調和", english: "Harmony", axisScores: [{ axis: "AC", pole: "C", score: 9 }, { axis: "DW", pole: "W", score: 6 }] },
  43: { japanese: "健康", english: "Health", axisScores: [{ axis: "DW", pole: "W", score: 10 }] },
  44: { japanese: "正直", english: "Honesty", axisScores: [{ axis: "AC", pole: "A", score: 7 }] },
  45: { japanese: "人間関係", english: "Human Relationships", axisScores: [{ axis: "AC", pole: "C", score: 10 }] },
  46: { japanese: "謙虚", english: "Humility", axisScores: [{ axis: "AC", pole: "C", score: 7 }] },
  47: { japanese: "自立", english: "Independence", axisScores: [{ axis: "AC", pole: "A", score: 9 }] },
  48: { japanese: "影響力", english: "Influence", axisScores: [{ axis: "DW", pole: "D", score: 8 }] },
  49: { japanese: "率先・主導権", english: "Initiative", axisScores: [{ axis: "DW", pole: "D", score: 8 }, { axis: "AC", pole: "A", score: 7 }] },
  50: { japanese: "革新性", english: "Innovativeness", axisScores: [{ axis: "ES", pole: "E", score: 8 }, { axis: "LI", pole: "I", score: 7 }] },
  51: { japanese: "誠実さ", english: "Integrity", axisScores: [{ axis: "ES", pole: "S", score: 7 }] },
  52: { japanese: "知性", english: "Intelligence", axisScores: [{ axis: "LI", pole: "L", score: 8 }] },
  53: { japanese: "おもしろい", english: "Interesting", axisScores: [{ axis: "LI", pole: "I", score: 7 }, { axis: "ES", pole: "E", score: 6 }] },
  54: { japanese: "親切さ", english: "Kindness", axisScores: [{ axis: "AC", pole: "C", score: 9 }, { axis: "DW", pole: "W", score: 6 }] },
  55: { japanese: "リーダーシップ", english: "Leadership", axisScores: [{ axis: "DW", pole: "D", score: 9 }, { axis: "AC", pole: "C", score: 6 }] },
  56: { japanese: "ロジック・論理", english: "Logic", axisScores: [{ axis: "LI", pole: "L", score: 10 }] },
  57: { japanese: "愛", english: "Love", axisScores: [{ axis: "AC", pole: "C", score: 10 }, { axis: "DW", pole: "W", score: 8 }] },
  58: { japanese: "几帳面", english: "Methodical", axisScores: [{ axis: "LI", pole: "L", score: 10 }] },
  59: { japanese: "心が広い・寛容さ", english: "Open Mind", axisScores: [{ axis: "ES", pole: "E", score: 7 }, { axis: "LI", pole: "I", score: 6 }] },
  60: { japanese: "楽観主義", english: "Optimism", axisScores: [{ axis: "DW", pole: "W", score: 8 }] },
  61: { japanese: "秩序", english: "Order", axisScores: [{ axis: "ES", pole: "S", score: 9 }, { axis: "LI", pole: "L", score: 8 }] },
  62: { japanese: "組織", english: "Organization", axisScores: [{ axis: "LI", pole: "L", score: 10 }, { axis: "ES", pole: "S", score: 6 }] },
  63: { japanese: "情熱", english: "Passion", axisScores: [{ axis: "DW", pole: "D", score: 8 }, { axis: "ES", pole: "E", score: 6 }] },
  64: { japanese: "心の平穏", english: "Peace of Mind", axisScores: [{ axis: "DW", pole: "W", score: 10 }] },
  65: { japanese: "平穏な人生", english: "Peaceful Life", axisScores: [{ axis: "DW", pole: "W", score: 9 }, { axis: "ES", pole: "S", score: 8 }] },
  66: { japanese: "根気・忍耐力", english: "Perseverance", axisScores: [{ axis: "DW", pole: "D", score: 8 }, { axis: "ES", pole: "S", score: 6 }] },
  67: { japanese: "個性", english: "Personality", axisScores: [{ axis: "LI", pole: "I", score: 7 }, { axis: "AC", pole: "A", score: 6 }] },
  68: { japanese: "計画", english: "Plan", axisScores: [{ axis: "LI", pole: "L", score: 10 }, { axis: "ES", pole: "S", score: 7 }] },
  69: { japanese: "遊び心", english: "Playful Mind", axisScores: [{ axis: "LI", pole: "I", score: 8 }, { axis: "ES", pole: "E", score: 6 }] },
  70: { japanese: "ポジティブさ", english: "Positive", axisScores: [{ axis: "DW", pole: "W", score: 8 }] },
  71: { japanese: "プライバシー", english: "Privacy", axisScores: [{ axis: "AC", pole: "A", score: 9 }] },
  72: { japanese: "プロフェッショナル", english: "Professionalism", axisScores: [{ axis: "DW", pole: "D", score: 7 }, { axis: "LI", pole: "L", score: 7 }] },
  73: { japanese: "進歩・進化", english: "Progress", axisScores: [{ axis: "DW", pole: "D", score: 8 }, { axis: "ES", pole: "E", score: 7 }] },
  74: { japanese: "慎重", english: "Prudence", axisScores: [{ axis: "ES", pole: "S", score: 9 }, { axis: "LI", pole: "L", score: 6 }] },
  75: { japanese: "合理性", english: "Rationality", axisScores: [{ axis: "LI", pole: "L", score: 9 }] },
  76: { japanese: "尊敬", english: "Respect", axisScores: [{ axis: "AC", pole: "C", score: 8 }] },
  77: { japanese: "自己認識", english: "Self Awarness", axisScores: [{ axis: "DW", pole: "W", score: 7 }] },
  78: { japanese: "自己犠牲", english: "Self Sacrifice", axisScores: [{ axis: "AC", pole: "C", score: 9 }] },
  79: { japanese: "責任感", english: "Sense of Responsibility", axisScores: [{ axis: "ES", pole: "S", score: 8 }, { axis: "DW", pole: "D", score: 6 }] },
  80: { japanese: "一体感", english: "Solidarity", axisScores: [{ axis: "AC", pole: "C", score: 9 }] },
  81: { japanese: "安定", english: "Stability", axisScores: [{ axis: "ES", pole: "S", score: 10 }] },
  82: { japanese: "ステータス・地位", english: "Status", axisScores: [{ axis: "DW", pole: "D", score: 9 }] },
  83: { japanese: "支援", english: "Supportiveness", axisScores: [{ axis: "AC", pole: "C", score: 9 }] },
  84: { japanese: "信頼", english: "Trust", axisScores: [{ axis: "AC", pole: "C", score: 10 }, { axis: "ES", pole: "S", score: 5 }] },
  85: { japanese: "勝利", english: "Victory", axisScores: [{ axis: "DW", pole: "D", score: 10 }] },
  86: { japanese: "富・財産", english: "Wealth", axisScores: [{ axis: "DW", pole: "D", score: 9 }] },
  87: { japanese: "身体的・精神的・社会的に\n満たされた状態", english: "Well Being", axisScores: [{ axis: "DW", pole: "W", score: 10 }] },
  88: { japanese: "知識・賢さ", english: "Wisdom", axisScores: [{ axis: "LI", pole: "L", score: 7 }] },
  89: { japanese: "仕事", english: "Work", axisScores: [{ axis: "DW", pole: "D", score: 8 }, { axis: "LI", pole: "L", score: 6 }] },
  90: { japanese: "美意識", english: "Aesthetic Sense", axisScores: [{ axis: "LI", pole: "I", score: 8 }] },
  91: { japanese: "直感", english: "Intuition", axisScores: [{ axis: "LI", pole: "I", score: 10 }] },
  92: { japanese: "正義", english: "Justice", axisScores: [{ axis: "LI", pole: "L", score: 7 }, { axis: "AC", pole: "C", score: 6 }] },
  93: { japanese: "偶然・偶発", english: "Serendipity", axisScores: [{ axis: "ES", pole: "E", score: 9 }, { axis: "LI", pole: "I", score: 8 }] },
}