import type { Axis, Pole, CardInfo as ScoringCardInfo } from "../valueAxisScoring";

export type CardInfo = ScoringCardInfo;

export function getCardImageUrl(cardId: number): string {
  return `/cards/card_${cardId.toString().padStart(2, "0")}.png`;
}

export const cardDict: { [id: number]: CardInfo } = {
  0:  { japanese: "海外就職", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "CS", pole: "C", score: 5 }, { axis: "UN", pole: "U", score: 2 }, { axis: "IT", pole: "I", score: 2 }] },
  1:  { japanese: "将来の夢への直結度", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "CS", pole: "C", score: 2 }] },
  2:  { japanese: "世界ランキング", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "CS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 3 }] },
  3:  { japanese: "大学の知名度", axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  4:  { japanese: "学問の専門性", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "CS", pole: "C", score: 1 }, { axis: "IT", pole: "I", score: 3 }] },
  5:  { japanese: "批判的思考力", axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "CS", pole: "C", score: 2 }, { axis: "IT", pole: "I", score: 3 }] },
  6:  { japanese: "答えのない問いを解く", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "C", score: 4 }, { axis: "IT", pole: "I", score: 2 }] },
  7:  { japanese: "実践型", axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "CS", pole: "C", score: 3 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 2 }] },
  8:  { japanese: "評価方法", axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "IT", pole: "I", score: 1 }] },
  9:  { japanese: "準備・計画努力型", axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "CS", pole: "S", score: 1 }, { axis: "IT", pole: "I", score: 4 }] },
  10: { japanese: "個人戦", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "C", score: 2 }, { axis: "IT", pole: "I", score: 5 }] },
  11: { japanese: "大学院進学率", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 1 }] },
  12: { japanese: "挫折経験", axisScores: [{ axis: "CS", pole: "C", score: 5 }, { axis: "IT", pole: "I", score: 3 }] },
  13: { japanese: "理系", axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "IT", pole: "I", score: 2 }] },
  14: { japanese: "留学スタイル（正規・交換）", axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "CS", pole: "C", score: 1 }] },
  15: { japanese: "留学期間", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "C", score: 2 }] },
  16: { japanese: "就職率", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "CS", pole: "S", score: 4 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 1 }] },
  17: { japanese: "キャリアの汎用性の高さ", axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "CS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 1 }] },
  18: { japanese: "資格", axisScores: [{ axis: "CL", pole: "C", score: 5 }, { axis: "CS", pole: "S", score: 4 }, { axis: "IT", pole: "I", score: 3 }] },
  19: { japanese: "前例の多さ", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "S", score: 5 }, { axis: "IT", pole: "T", score: 2 }] },
  20: { japanese: "コスパ・タイパ", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 2 }] },
  21: { japanese: "英語力", axisScores: [{ axis: "CL", pole: "C", score: 3 }, { axis: "CS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 1 }] },
  22: { japanese: "言語の学びやすさ", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "S", score: 4 }, { axis: "IT", pole: "T", score: 1 }] },
  23: { japanese: "学費", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "S", score: 4 }, { axis: "IT", pole: "I", score: 1 }] },
  24: { japanese: "物価", axisScores: [{ axis: "CS", pole: "S", score: 3 }, { axis: "UN", pole: "N", score: 1 }] },
  25: { japanese: "現地での収入源", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 2 }] },
  26: { japanese: "奨学金", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "S", score: 3 }, { axis: "IT", pole: "I", score: 2 }] },
  27: { japanese: "学校のサポート", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "S", score: 5 }, { axis: "IT", pole: "T", score: 3 }] },
  28: { japanese: "団体戦", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "S", score: 1 }, { axis: "IT", pole: "T", score: 5 }] },
  29: { japanese: "文系", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "S", score: 1 }, { axis: "IT", pole: "T", score: 2 }] },
  30: { japanese: "ガクチカ", axisScores: [{ axis: "CL", pole: "C", score: 4 }, { axis: "CS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 1 }] },
  31: { japanese: "地方", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "CS", pole: "C", score: 3 }, { axis: "UN", pole: "N", score: 5 }, { axis: "IT", pole: "I", score: 1 }] },
  32: { japanese: "街の雰囲気（歴史的・モダン）", axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "CS", pole: "S", score: 1 }, { axis: "UN", pole: "N", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  33: { japanese: "自然の近さ", axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "UN", pole: "N", score: 5 }] },
  34: { japanese: "国際性", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "C", score: 2 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "T", score: 3 }] },
  35: { japanese: "多様性", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "CS", pole: "C", score: 3 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "T", score: 3 }] },
  36: { japanese: "留学先の国民性", axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "IT", pole: "T", score: 2 }] },
  37: { japanese: "英語のアクセント", axisScores: [{ axis: "CS", pole: "C", score: 2 }] },
  38: { japanese: "アルバイト", axisScores: [{ axis: "CS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  39: { japanese: "課外活動", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "T", score: 4 }] },
  40: { japanese: "スポーツ", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "IT", pole: "T", score: 4 }] },
  41: { japanese: "現地の友人関係", axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "CS", pole: "C", score: 1 }, { axis: "IT", pole: "T", score: 5 }] },
  42: { japanese: "日本文化の発信", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "CS", pole: "C", score: 2 }, { axis: "IT", pole: "T", score: 4 }] },
  43: { japanese: "精神的成長", axisScores: [{ axis: "CS", pole: "C", score: 4 }, { axis: "IT", pole: "I", score: 3 }] },
  44: { japanese: "キャラ変（から破り）", axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "CS", pole: "C", score: 4 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 2 }] },
  45: { japanese: "芸術", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "CS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 3 }, { axis: "IT", pole: "I", score: 1 }] },
  46: { japanese: "都市", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "UN", pole: "U", score: 5 }, { axis: "IT", pole: "T", score: 1 }] },
  47: { japanese: "部活", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "IT", pole: "T", score: 5 }] },
  48: { japanese: "日本人の少なさ", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "C", score: 5 }, { axis: "UN", pole: "N", score: 1 }, { axis: "IT", pole: "I", score: 4 }] },
  49: { japanese: "最先端カルチャー", axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "CS", pole: "C", score: 2 }, { axis: "UN", pole: "U", score: 5 }, { axis: "IT", pole: "T", score: 2 }] },
  50: { japanese: "治安の良さ", axisScores: [{ axis: "CS", pole: "S", score: 5 }] },
  51: { japanese: "衛生面・綺麗さ", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "S", score: 4 }, { axis: "UN", pole: "U", score: 1 }] },
  52: { japanese: "医療技術", axisScores: [{ axis: "CS", pole: "S", score: 5 }, { axis: "UN", pole: "U", score: 1 }] },
  53: { japanese: "気候の快適さ", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "CS", pole: "S", score: 3 }] },
  54: { japanese: "冷暖房", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "S", score: 4 }, { axis: "UN", pole: "U", score: 1 }, { axis: "IT", pole: "I", score: 1 }] },
  55: { japanese: "住居（寮・シェアハウス・ホームステイ）", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 3 }] },
  56: { japanese: "施設の充実度", axisScores: [{ axis: "CS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 2 }] },
  57: { japanese: "日本からの距離", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  58: { japanese: "日本との時差", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  59: { japanese: "家族や恋人との連絡頻度", axisScores: [{ axis: "CL", pole: "L", score: 2 }, { axis: "CS", pole: "S", score: 4 }, { axis: "IT", pole: "T", score: 3 }] },
  60: { japanese: "親日性", axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "CS", pole: "S", score: 4 }, { axis: "IT", pole: "T", score: 2 }] },
  61: { japanese: "日本との政治的関係", axisScores: [{ axis: "CS", pole: "S", score: 3 }] },
  62: { japanese: "食の豊かさ", axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "CS", pole: "S", score: 2 }, { axis: "UN", pole: "U", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  63: { japanese: "娯楽", axisScores: [{ axis: "CL", pole: "L", score: 5 }, { axis: "CS", pole: "S", score: 1 }, { axis: "UN", pole: "U", score: 4 }, { axis: "IT", pole: "T", score: 3 }] },
  64: { japanese: "ナイトライフ", axisScores: [{ axis: "CL", pole: "L", score: 5 }, { axis: "CS", pole: "C", score: 2 }, { axis: "UN", pole: "U", score: 5 }, { axis: "IT", pole: "T", score: 4 }] },
  65: { japanese: "SNS投稿（留学Vlog）", axisScores: [{ axis: "CL", pole: "L", score: 3 }, { axis: "CS", pole: "C", score: 1 }, { axis: "UN", pole: "U", score: 4 }, { axis: "IT", pole: "T", score: 2 }] },
  66: { japanese: "私生活と勉強のバランス", axisScores: [{ axis: "CL", pole: "L", score: 4 }, { axis: "CS", pole: "S", score: 3 }, { axis: "IT", pole: "T", score: 1 }] },
  67: { japanese: "クラス規模", axisScores: [{ axis: "CL", pole: "C", score: 1 }, { axis: "CS", pole: "S", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  68: { japanese: "教授との距離", axisScores: [{ axis: "CL", pole: "C", score: 2 }, { axis: "CS", pole: "S", score: 2 }, { axis: "IT", pole: "T", score: 2 }] },
  69: { japanese: "移動手段", axisScores: [{ axis: "CL", pole: "L", score: 1 }, { axis: "CS", pole: "S", score: 3 }, { axis: "UN", pole: "U", score: 3 }] },
};
