export function getCardImageUrl(cardId: number): string {
  return `/cards/card_${cardId.toString().padStart(2, "0")}.png`;
}

type CardInfo = { japanese: string };

export const cardDict: { [id: number]: CardInfo } = {
  0:  { japanese: "海外就職" },
  1:  { japanese: "将来の夢への直結度" },
  2:  { japanese: "世界ランキング" },
  3:  { japanese: "大学の知名度" },
  4:  { japanese: "学問の専門性" },
  5:  { japanese: "批判的思考力" },
  6:  { japanese: "答えのない問いを解く" },
  7:  { japanese: "実践型" },
  8:  { japanese: "評価方法" },
  9:  { japanese: "準備・計画努力型" },
  10: { japanese: "個人戦" },
  11: { japanese: "大学院進学率" },
  12: { japanese: "挫折経験" },
  13: { japanese: "理系" },
  14: { japanese: "留学スタイル（正規・交換）" },
  15: { japanese: "留学期間" },
  16: { japanese: "就職率" },
  17: { japanese: "キャリアの汎用性の高さ" },
  18: { japanese: "資格" },
  19: { japanese: "前例の多さ" },
  20: { japanese: "コスパ・タイパ" },
  21: { japanese: "英語力" },
  22: { japanese: "言語の学びやすさ" },
  23: { japanese: "学費" },
  24: { japanese: "物価" },
  25: { japanese: "現地での収入源" },
  26: { japanese: "奨学金" },
  27: { japanese: "学校のサポート" },
  28: { japanese: "団体戦" },
  29: { japanese: "文系" },
  30: { japanese: "ガクチカ" },
  31: { japanese: "地方" },
  32: { japanese: "街の雰囲気（歴史的・モダン）" },
  33: { japanese: "自然の近さ" },
  34: { japanese: "国際性" },
  35: { japanese: "多様性" },
  36: { japanese: "留学先の国民性" },
  37: { japanese: "英語のアクセント" },
  38: { japanese: "アルバイト" },
  39: { japanese: "課外活動" },
  40: { japanese: "スポーツ" },
  41: { japanese: "現地の友人関係" },
  42: { japanese: "日本文化の発信" },
  43: { japanese: "精神的成長" },
  44: { japanese: "キャラ変（から破り）" },
  45: { japanese: "芸術" },
  46: { japanese: "都市" },
  47: { japanese: "部活" },
  48: { japanese: "日本人の少なさ" },
  49: { japanese: "最先端カルチャー" },
  50: { japanese: "治安の良さ" },
  51: { japanese: "衛生面・綺麗さ" },
  52: { japanese: "医療技術" },
  53: { japanese: "気候の快適さ" },
  54: { japanese: "冷暖房" },
  55: { japanese: "住居（寮・シェアハウス・ホームステイ）" },
  56: { japanese: "施設の充実度" },
  57: { japanese: "日本からの距離" },
  58: { japanese: "日本との時差" },
  59: { japanese: "家族や恋人との連絡頻度" },
  60: { japanese: "親日性" },
  61: { japanese: "日本との政治的関係" },
  62: { japanese: "食の豊かさ" },
  63: { japanese: "娯楽" },
  64: { japanese: "ナイトライフ" },
  65: { japanese: "SNS投稿（留学Vlog）" },
  66: { japanese: "私生活と勉強のバランス" },
  67: { japanese: "クラス規模" },
  68: { japanese: "教授との距離" },
  69: { japanese: "移動手段" },
};
