export function getCardImageUrl(cardId: number): string {
  return `/cards/card_${cardId.toString().padStart(2, "0")}.webp`;
}

type CardInfo = { japanese: string };

export const cardDict: { [id: number]: CardInfo } = {
  0: { japanese: '海外就職' },
  1: { japanese: '将来の夢への直結度' },
  2: { japanese: '世界ランキング' },
  3: { japanese: '大学の知名度' },
  4: { japanese: '学問の専門性' },
  5: { japanese: '批判的思考力' },
  6: { japanese: '成績' },
  7: { japanese: '実践型' },
  8: { japanese: '評価方法' },
  9: { japanese: '準備・計画努力型' },
  10: { japanese: '大学院進学率' },
  11: { japanese: '挫折経験' },
  12: { japanese: '留学スタイル（正規・交換）' },
  13: { japanese: '留学期間' },
  14: { japanese: '就職率' },
  15: { japanese: 'キャリアの汎用性の高さ' },
  16: { japanese: '資格' },
  17: { japanese: '前例の多さ' },
  18: { japanese: 'コスパ・タイパ' },
  19: { japanese: '英語力' },
  20: { japanese: '言語の学びやすさ' },
  21: { japanese: '学費' },
  22: { japanese: '物価' },
  23: { japanese: '現地での収入源' },
  24: { japanese: '奨学金' },
  25: { japanese: '学校のサポート' },
  26: { japanese: 'ガクチカ' },
  27: { japanese: '地方' },
  28: { japanese: '街の雰囲気（歴史的・モダン）' },
  29: { japanese: '自然の近さ' },
  30: { japanese: '国際性' },
  31: { japanese: '多様性' },
  32: { japanese: '留学先の国民性' },
  33: { japanese: '英語のアクセント' },
  34: { japanese: 'アルバイト' },
  35: { japanese: '課外活動' },
  36: { japanese: 'スポーツ' },
  37: { japanese: '現地の友人関係' },
  38: { japanese: '精神的成長' },
  39: { japanese: 'キャラ変（から破り）' },
  40: { japanese: '芸術' },
  41: { japanese: '都市' },
  42: { japanese: '部活' },
  43: { japanese: '日本人の少なさ' },
  44: { japanese: '治安の良さ' },
  45: { japanese: '衛生面・綺麗さ' },
  46: { japanese: '医療技術' },
  47: { japanese: '気候の快適さ' },
  48: { japanese: '住居（寮・シェアハウス・ホームステイ）' },
  49: { japanese: '施設の充実度' },
  50: { japanese: '日本からの距離' },
  51: { japanese: '日本との時差' },
  52: { japanese: '家族や恋人との連絡頻度' },
  53: { japanese: '親日性' },
  54: { japanese: '日本との政治的関係' },
  55: { japanese: '食の豊かさ' },
  56: { japanese: '娯楽' },
  57: { japanese: 'ナイトライフ' },
  58: { japanese: '私生活と勉強のバランス' },
  59: { japanese: 'クラス規模' },
  60: { japanese: '教授との距離' },
  61: { japanese: '移動手段' },
};
