export function getCardImageUrl(cardId: number): string {
  return `/cards/card_${cardId.toString().padStart(2, "0")}.png`;
}

type CardInfo = { japanese: string; english: string };

export const cardDict: { [id: number]: CardInfo } = {
  0: {japanese: "時間を大切に", english: "Time Conscious"},
  1: {japanese: "承認", english: "Acknowledgement"},
  2: {japanese: "行動", english: "Action"},
  3: {japanese: "冒険", english: "Adventure"},
  4: {japanese: "利他的", english: "Altruistic"},
  5: {japanese: "志・野心", english: "Ambition"},
  6: {japanese: "向上心", english: "Aspiration"},
  7: {japanese: "自律", english: "Autonomy"},
  8: {japanese: "挑戦", english: "Challenge"},
  9: {japanese: "変化", english: "Change"},
  10: {japanese: "心地よさ", english: "Comfortableness"},
  11: {japanese: "コミットメント", english: "Commitment"},
  12: {japanese: "コミュニケーション", english: "Communication"},
  13: {japanese: "冷静", english: "Composure"},
  14: {japanese: "一貫性", english: "Consistency"},
  15: {japanese: "貢献", english: "Contribution"},
  16: {japanese: "協力", english: "Cooperation"},
  17: {japanese: "礼儀・礼節", english: "Courtesy"},
  18: {japanese: "創造性", english: "Creativity"},
  19: {japanese: "好奇心", english: "Curiousity"},
  20: {japanese: "規律", english: "Discipline"},
  21: {japanese: "多様性", english: "Diversity"},
  22: {japanese: "義理人情", english: "Duty and Humanity"},
  23: {japanese: "有効性・効率", english: "Effectiveness"},
  24: {japanese: "努力", english: "Effort"},
  25: {japanese: "共感", english: "Empathy"},
  26: {japanese: "エンパワーメント", english: "Empowerment"},
  27: {japanese: "励まし", english: "Encouregement"},
  28: {japanese: "平等・公平性", english: "Equality"},
  29: {japanese: "躍動的な人生", english: "Exciting Life"},
  30: {japanese: "経験", english: "Experience"},
  31: {japanese: "公正性・公平性", english: "Fairness"},
  32: {japanese: "家族", english: "Family"},
  33: {japanese: "フォロワーシップ", english: "Followership"},
  34: {japanese: "率直さ", english: "Frankness"},
  35: {japanese: "自由", english: "Freedom"},
  36: {japanese: "友情・仲間", english: "Friendship"},
  37: {japanese: "全力", english: "Full Strength"},
  38: {japanese: "優しさ", english: "Gentleness"},
  39: {japanese: "グローバル", english: "Global"},
  40: {japanese: "感謝", english: "Gratitude"},
  41: {japanese: "成長", english: "Growth"},
  42: {japanese: "調和", english: "Harmony"},
  43: {japanese: "健康", english: "Health"},
  44: {japanese: "正直", english: "Honesty"},
  45: {japanese: "人間関係", english: "Human Relationships"},
  46: {japanese: "謙虚", english: "Humility"},
  47: {japanese: "自立", english: "Independence"},
  48: {japanese: "影響力", english: "Influence"},
  49: {japanese: "率先・主導権", english: "Initiative"},
  50: {japanese: "革新性", english: "Innovativeness"},
  51: {japanese: "誠実さ", english: "Integrity"},
  52: {japanese: "知性", english: "Intelligence"},
  53: {japanese: "おもしろい", english: "Interesting"},
  54: {japanese: "親切さ", english: "Kindness"},
  55: {japanese: "リーダーシップ", english: "Leadership"},
  56: {japanese: "ロジック・論理", english: "Logic"},
  57: {japanese: "愛", english: "Love"},
  58: {japanese: "几帳面", english: "Methodical"},
  59: {japanese: "心が広い・寛容さ", english: "Open Mind"},
  60: {japanese: "楽観主義", english: "Optimism"},
  61: {japanese: "秩序", english: "Order"},
  62: {japanese: "組織", english: "Organization"},
  63: {japanese: "情熱", english: "Passion"},
  64: {japanese: "心の平穏", english: "Peace of Mind"},
  65: {japanese: "平穏な人生", english: "Peaceful Life"},
  66: {japanese: "根気・忍耐力", english: "Perseverance"},
  67: {japanese: "個性", english: "Personality"},
  68: {japanese: "計画", english: "Plan"},
  69: {japanese: "遊び心", english: "Playful Mind"},
  70: {japanese: "ポジティブさ", english: "Positive"},
  71: {japanese: "プライバシー", english: "Privacy"},
  72: {japanese: "プロフェッショナル", english: "Professionalism"},
  73: {japanese: "進歩・進化", english: "Progress"},
  74: {japanese: "慎重", english: "Prudence"},
  75: {japanese: "合理性", english: "Rationality"},
  76: {japanese: "尊敬", english: "Respect"},
  77: {japanese: "自己認識", english: "Self Awarness"},
  78: {japanese: "自己犠牲", english: "Self Sacrifice"},
  79: {japanese: "責任感", english: "Sense of Responsibility"},
  80: {japanese: "一体感", english: "Solidarity"},
  81: {japanese: "安定", english: "Stability"},
  82: {japanese: "ステータス・地位", english: "Status"},
  83: {japanese: "支援", english: "Supportiveness"},
  84: {japanese: "信頼", english: "Trust"},
  85: {japanese: "勝利", english: "Victory"},
  86: {japanese: "富・財産", english: "Wealth"},
  87: {japanese: "身体的・精神的・社会的に\n満たされた状態", english: "Well Being"},
  88: {japanese: "知識・賢さ", english: "Wisdom"},
  89: {japanese: "仕事", english: "Work"},
  90: {japanese: "美意識", english: "Aesthetic Sense"},
  91: {japanese: "直感", english: "Intuition"},
  92: {japanese: "正義", english: "Justice"},
  93: {japanese: "偶然・偶発", english: "Serendipity"},
}